/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiScriptsRouteImport } from './routes/api/scripts'
import { Route as ApiCheckRouteImport } from './routes/api/check'
import { Route as ApiPublicScriptLoaderRouteImport } from './routes/api/public/script-loader'
import { Route as ApiPublicScriptRouteImport } from './routes/api/public/script'
import { Route as ApiPublicRobloxRouteImport } from './routes/api/public/roblox'
import { Route as ApiPublicRedisPingRouteImport } from './routes/api/public/redis-ping'
import { Route as ApiPublicLoaderCheckRouteImport } from './routes/api/public/loader-check'
import { Route as ApiPublicFeedbackRouteImport } from './routes/api/public/feedback'
import { Route as ApiPublicScriptsIndexRouteImport } from './routes/api/public/scripts.index'
import { Route as ApiPublicScriptsSearchRouteImport } from './routes/api/public/scripts.search'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScriptsRoute = ApiScriptsRouteImport.update({
  id: '/api/scripts',
  path: '/api/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckRoute = ApiCheckRouteImport.update({
  id: '/api/check',
  path: '/api/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScriptLoaderRoute = ApiPublicScriptLoaderRouteImport.update({
  id: '/api/public/script-loader',
  path: '/api/public/script-loader',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScriptRoute = ApiPublicScriptRouteImport.update({
  id: '/api/public/script',
  path: '/api/public/script',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobloxRoute = ApiPublicRobloxRouteImport.update({
  id: '/api/public/roblox',
  path: '/api/public/roblox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRedisPingRoute = ApiPublicRedisPingRouteImport.update({
  id: '/api/public/redis-ping',
  path: '/api/public/redis-ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLoaderCheckRoute = ApiPublicLoaderCheckRouteImport.update({
  id: '/api/public/loader-check',
  path: '/api/public/loader-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedbackRoute = ApiPublicFeedbackRouteImport.update({
  id: '/api/public/feedback',
  path: '/api/public/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScriptsIndexRoute = ApiPublicScriptsIndexRouteImport.update({
  id: '/api/public/scripts/',
  path: '/api/public/scripts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScriptsSearchRoute = ApiPublicScriptsSearchRouteImport.update({
  id: '/api/public/scripts/search',
  path: '/api/public/scripts/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/check': typeof ApiCheckRoute
  '/api/scripts': typeof ApiScriptsRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/loader-check': typeof ApiPublicLoaderCheckRoute
  '/api/public/redis-ping': typeof ApiPublicRedisPingRoute
  '/api/public/roblox': typeof ApiPublicRobloxRoute
  '/api/public/script': typeof ApiPublicScriptRoute
  '/api/public/script-loader': typeof ApiPublicScriptLoaderRoute
  '/api/public/scripts/search': typeof ApiPublicScriptsSearchRoute
  '/api/public/scripts/': typeof ApiPublicScriptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/check': typeof ApiCheckRoute
  '/api/scripts': typeof ApiScriptsRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/loader-check': typeof ApiPublicLoaderCheckRoute
  '/api/public/redis-ping': typeof ApiPublicRedisPingRoute
  '/api/public/roblox': typeof ApiPublicRobloxRoute
  '/api/public/script': typeof ApiPublicScriptRoute
  '/api/public/script-loader': typeof ApiPublicScriptLoaderRoute
  '/api/public/scripts/search': typeof ApiPublicScriptsSearchRoute
  '/api/public/scripts': typeof ApiPublicScriptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/check': typeof ApiCheckRoute
  '/api/scripts': typeof ApiScriptsRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/loader-check': typeof ApiPublicLoaderCheckRoute
  '/api/public/redis-ping': typeof ApiPublicRedisPingRoute
  '/api/public/roblox': typeof ApiPublicRobloxRoute
  '/api/public/script': typeof ApiPublicScriptRoute
  '/api/public/script-loader': typeof ApiPublicScriptLoaderRoute
  '/api/public/scripts/search': typeof ApiPublicScriptsSearchRoute
  '/api/public/scripts/': typeof ApiPublicScriptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/api/check'
    | '/api/scripts'
    | '/api/public/feedback'
    | '/api/public/loader-check'
    | '/api/public/redis-ping'
    | '/api/public/roblox'
    | '/api/public/script'
    | '/api/public/script-loader'
    | '/api/public/scripts/search'
    | '/api/public/scripts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/api/check'
    | '/api/scripts'
    | '/api/public/feedback'
    | '/api/public/loader-check'
    | '/api/public/redis-ping'
    | '/api/public/roblox'
    | '/api/public/script'
    | '/api/public/script-loader'
    | '/api/public/scripts/search'
    | '/api/public/scripts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/api/check'
    | '/api/scripts'
    | '/api/public/feedback'
    | '/api/public/loader-check'
    | '/api/public/redis-ping'
    | '/api/public/roblox'
    | '/api/public/script'
    | '/api/public/script-loader'
    | '/api/public/scripts/search'
    | '/api/public/scripts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiCheckRoute: typeof ApiCheckRoute
  ApiScriptsRoute: typeof ApiScriptsRoute
  ApiPublicFeedbackRoute: typeof ApiPublicFeedbackRoute
  ApiPublicLoaderCheckRoute: typeof ApiPublicLoaderCheckRoute
  ApiPublicRedisPingRoute: typeof ApiPublicRedisPingRoute
  ApiPublicRobloxRoute: typeof ApiPublicRobloxRoute
  ApiPublicScriptRoute: typeof ApiPublicScriptRoute
  ApiPublicScriptLoaderRoute: typeof ApiPublicScriptLoaderRoute
  ApiPublicScriptsSearchRoute: typeof ApiPublicScriptsSearchRoute
  ApiPublicScriptsIndexRoute: typeof ApiPublicScriptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scripts': {
      id: '/api/scripts'
      path: '/api/scripts'
      fullPath: '/api/scripts'
      preLoaderRoute: typeof ApiScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check': {
      id: '/api/check'
      path: '/api/check'
      fullPath: '/api/check'
      preLoaderRoute: typeof ApiCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/script-loader': {
      id: '/api/public/script-loader'
      path: '/api/public/script-loader'
      fullPath: '/api/public/script-loader'
      preLoaderRoute: typeof ApiPublicScriptLoaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/script': {
      id: '/api/public/script'
      path: '/api/public/script'
      fullPath: '/api/public/script'
      preLoaderRoute: typeof ApiPublicScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roblox': {
      id: '/api/public/roblox'
      path: '/api/public/roblox'
      fullPath: '/api/public/roblox'
      preLoaderRoute: typeof ApiPublicRobloxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/redis-ping': {
      id: '/api/public/redis-ping'
      path: '/api/public/redis-ping'
      fullPath: '/api/public/redis-ping'
      preLoaderRoute: typeof ApiPublicRedisPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/loader-check': {
      id: '/api/public/loader-check'
      path: '/api/public/loader-check'
      fullPath: '/api/public/loader-check'
      preLoaderRoute: typeof ApiPublicLoaderCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feedback': {
      id: '/api/public/feedback'
      path: '/api/public/feedback'
      fullPath: '/api/public/feedback'
      preLoaderRoute: typeof ApiPublicFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scripts/': {
      id: '/api/public/scripts/'
      path: '/api/public/scripts'
      fullPath: '/api/public/scripts/'
      preLoaderRoute: typeof ApiPublicScriptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scripts/search': {
      id: '/api/public/scripts/search'
      path: '/api/public/scripts/search'
      fullPath: '/api/public/scripts/search'
      preLoaderRoute: typeof ApiPublicScriptsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiCheckRoute: ApiCheckRoute,
  ApiScriptsRoute: ApiScriptsRoute,
  ApiPublicFeedbackRoute: ApiPublicFeedbackRoute,
  ApiPublicLoaderCheckRoute: ApiPublicLoaderCheckRoute,
  ApiPublicRedisPingRoute: ApiPublicRedisPingRoute,
  ApiPublicRobloxRoute: ApiPublicRobloxRoute,
  ApiPublicScriptRoute: ApiPublicScriptRoute,
  ApiPublicScriptLoaderRoute: ApiPublicScriptLoaderRoute,
  ApiPublicScriptsSearchRoute: ApiPublicScriptsSearchRoute,
  ApiPublicScriptsIndexRoute: ApiPublicScriptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
